spring.datasource.url=${DB_URL:postgresql://neondb_owner:npg_fT6wlXE0yoSL@ep-gentle-king-asa66781-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_fT6wlXE0yoSL}

spring.datasource.driver-class-name=org.postgresql.Driver

aws.s3.bucket=${AWS_S3_BUCKET}
aws.eventBridge.bus=default

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB